[package]
name = "flux-core"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "lib/pb",
]
resolver = "2"

[dependencies]
anyhow = "1.0.89"
config = { version = "0.14", default-features = false, features = ["toml"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"

axum = "0.7.6"

tokio = { version = "1.40.0", features = ["full"] }

tonic = "0.12.2"
tonic-health = "0.12.2"
tonic-reflection = "0.12.2"

async-nats = "0.36.0"

flux-core-pb = { path = "lib/pb" }

