[package]
name = "flux-core"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["lib/api", "lib/migration"]
resolver = "2"

[dependencies]
flux-core-api = { path = "lib/api" }

anyhow = "1.0.89"
thiserror = "1.0.64"
futures-lite = "2.3.0"
config = { version = "0.14", default-features = false, features = ["toml"] }
validator = { version = "0.18.1", features = ["derive"] }
uuid = { version = "1.10.0", features = ["v7"] }
chrono = "0.4.38"

axum = "0.7.7"

tokio = { version = "1.40.0", features = ["full"] }

prost = "0.13.3"
tonic = "0.12.3"
tonic-health = "0.12.3"
tonic-reflection = "0.12.3"

async-nats = "0.36.0"

sea-orm = { version = "1.0.1", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
] }

serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
bytes = "1.7.2"
