[package]
name = "flux-core"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["lib/api", "lib/migration"]
resolver = "2"

[dependencies]
flux-core-api = { path = "lib/api" }
flux-lib = { git = "https://github.com/thefluxapp/flux-lib.git" }

anyhow = "1.0.94"
thiserror = "2.0.8"
futures-lite = "2.5.0"
config = { version = "0.14", default-features = false, features = ["toml"] }
validator = { version = "0.18.1", features = ["derive"] }
uuid = { version = "1.11.0", features = ["v7"] }
chrono = "0.4.39"
log = "0.4.22"
bytes = "1.9.0"
itertools = "0.13.0"

axum = "0.7.9"

tokio = { version = "1.42.0", features = ["full"] }

prost = "0.13.4"
prost-types = "0.13.4"
tonic = "0.12.3"
tonic-health = "0.12.3"
tonic-reflection = "0.12.3"

async-nats = "0.36.0"

sea-orm = { version = "1.1.2", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
] }

serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
